slideshow/blueprints/display/models.py
from slideshow.extensions import db
from slideshow.utils.sql import SQLMixin
from slideshow.utils import generate_random_string


class Display(SQLMixin, db.Model):
    __tablename__ = 'display'
    public_id = db.Column(db.String(10), unique=True, nullable=False)
    location = db.Column(db.String(64))
    active = db.Column(db.Boolean, default=True)

    def deactivate(self):
        self.active = False
        self.save()

    def activate(self):
        self.active = True
        self.save()

    def __init__(self, location="Default"):
        self.public_id = generate_random_string(10)
        self.location = location
        self.active = True

slideshow/blueprints/display/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, FileField, SubmitField
from wtforms.validators import DataRequired


class DisplayForm(FlaskForm):
    """
    Form for creating a new display.
    """
    location = StringField('Location', validators=[DataRequired()])
    image = FileField('Image', validators=[DataRequired()])
    submit = SubmitField('Create')


class EditDisplayForm(FlaskForm):
    """
    Form for editing a display.
    """
    location = StringField('Location', validators=[DataRequired()])
    image = FileField('Image', validators=[DataRequired()])
    active = BooleanField('Active')
    submit = SubmitField('Update')

slideshow/blueprints/display/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, abort
from flask_login import login_required, current_user

from .models import Display
from .forms import DisplayForm, EditDisplayForm

bp = Blueprint('display', __name__, template_folder='templates', url_prefix='/display/')


@bp.get('/')
@login_required
def display_list():
    displays = Display.query.all()
    return render_template('display/display_list.html', displays=displays)


@bp.get('create_display')
@login_required
def create_display():
    display = Display(location='Default')
    display.save()
    return redirect(url_for('display.display_list'))


@bp.get('/deactivate_display/<public_id>')
@login_required
def deactivate_display(public_id):
    display = Display.query.filter_by(public_id=public_id).first()
    display.deactivate()
    return redirect(url_for('display.display_list'))


@bp.get('/activate_display/<public_id>')
@login_required
def activate_display(public_id):
    display = Display.query.filter_by(public_id=public_id).first()
    display.activate()
    return redirect(url_for('display.display_list'))


@bp.get('/delete_display/<public_id>')
@login_required
def delete_display(public_id):
    display = Display.query.filter_by(public_id=public_id).first()
    display.delete()
    return redirect(url_for('display.display_list'))

slideshow/blueprints/display/templates/display/display_list.html
{% extends 'layouts/base.html' %}


{% block main %}

    {% if displays %}

        <section>
            <div class="row">
                {% for display in displays %}
                    <div class="col s12 m3">
                        <div class="card blue-grey darken-4 hoverable">
                            <div class="card-content white-text">
                                <span class="card-title">ID: {{ display.public_id }}</span>
                                <ul>
                                    <li>
                                        <p>Location: {{ display.location }}</p>
                                    </li>
                                    <li>
                                        <p>Active: {{ display.active }}</p>
                                    </li>
                                    <li>
                                        <p>Slider ID: None</p>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-action center-align">
                                {% if display.active %}
                                    <a href="{{ url_for('display.deactivate_display', public_id=display.public_id) }}"
                                       class="btn yellow black-text">Deactivate</a>
                                {% else %}
                                    <a href="{{ url_for('display.activate_display', public_id=display.public_id) }}"
                                       class="left btn green white-text">Activate</a>
                                {% endif %}
                                <a href="#deleteDisplayModal{{ display.public_id }}"
                                   class="btn small red modal-trigger">Delete</a>
                            </div>
                        </div>
                    </div>

                    <div id="deleteDisplayModal{{ display.public_id }}" class="modal">
                        <div class="modal-content">
                            <h4>Delete Display : {{ display.public_id }}</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab alias aspernatur debitis
                                enim eveniet expedita, libero maiores necessitatibus nihil obcaecati quaerat quia rerum
                                soluta. Ex id in laboriosam molestiae. Culpa, perferendis, praesentium?</p>
                        </div>

                        <div class="modal-footer">
                            <a href="{{ url_for('display.delete_display', public_id=display.public_id) }}"
                               class="modal-close waves-effect waves-green btn-flat">Agree</a>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </section>


    {% else %}
        <h1>No Displays Available.</h1>
    {% endif %}


    <div class="fixed-action-btn">
        <a href="{{ url_for('display.create_display') }}"
           class="btn-floating btn-large blue accent-3 pulse modal-trigger">
            <i class="large material-icons">add</i>
        </a>
    </div>

{% endblock %}