slideshow/blueprints/core/views.py
from flask import render_template, request, redirect, url_for, flash, jsonify, Blueprint
from werkzeug.utils import secure_filename
from flask_login import login_required
import os

from slideshow.extensions import db
from slideshow.utils import allowed_file_extensions, get_file_extension, generate_uuid
from .models import Content

from config import UPLOAD_FOLDER

bp = Blueprint('core', __name__, template_folder='templates')

rotation_speed = 10000  # in miliseconds
upload_folder = UPLOAD_FOLDER


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})


@bp.get('/')
@login_required
def index():
    """
    Displays the index page.
    """
    return render_template('index.html')


@bp.get('/login')
def login():
    """
    Displays the login page.
    """
    return redirect(url_for('user.login'))


@bp.get('/register')
def register():
    """
    Displays the register page.
    """
    return redirect(url_for('user.register'))


@bp.get('/setup')
@login_required
def setup():
    """
    Displays the setup page.
    """
    contents = Content.query.all()
    return render_template('setup.html', contents=contents, rotation_speed=rotation_speed // 1000)


@bp.get('/slideshow')
def slideshow():
    """
    Displays the slideshow page.
    """
    contents = Content.query.filter_by(active=True).all()

    return render_template(
        'slideshow.html',
        contents=contents,
        rotation_speed=rotation_speed,
    )


@bp.post('/alter_rotation_speed')
def alter_rotation_speed():
    """
    Changes the rotation speed of the slideshow.
    """
    global rotation_speed

    try:
        rotation_speed = float(
            request.form.to_dict()['alter_rotation_speed']) * 1000
    except Exception as e:
        flash('Please enter a number')

    return redirect(url_for('core.setup'))


@bp.post('/upload_file/')
@login_required
def upload_file():
    """
    Uploads a file to the server.
    """
    file = request.files['file']

    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)

    if file and allowed_file_extensions(file.filename):
        # Upload the file to the uploads folder
        file_ext = get_file_extension(file.filename)
        filename = secure_filename(generate_uuid() + '.' + file_ext)
        file.save(os.path.join(upload_folder, filename))
        flash('File uploaded successfully')

        # Create a new content object
        content = Content(type='file', path=filename)
        db.session.add(content)
        db.session.commit()

        return redirect(url_for('core.setup'))


@bp.post('/remove_content')
@login_required
def remove_content():
    """
    Removes a content object from the server.
    Removes the file from the uploads' folder.
    """
    content_id = request.form.get('content_id')
    content = Content.query.filter_by(path=content_id)
    cont_object = content.first()

    if cont_object.type == 'file':
        os.remove(f'{upload_folder}/{cont_object.path}')
        content.delete()
    else:
        content.delete()
    db.session.commit()
    return redirect(url_for('core.setup'))


@bp.post('/upload_link')
@login_required
def upload_link():
    """
    Adds a link to the database.
    """
    link = request.form.to_dict()['upload_link']

    if link:
        # Create a new content object
        content = Content(type='link', path=link)
        db.session.add(content)
        db.session.commit()

        return redirect(url_for('core.setup'))
    else:
        flash('Please enter a link')
        return redirect(url_for('core.setup'))

slideshow/blueprints/user/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
from flask_login import current_user, login_user, logout_user, login_required

from .forms import RegisterForm, LoginForm, EditProfileForm
from .models import User

bp = Blueprint('user', __name__, template_folder='templates', url_prefix='/user/')


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})


@bp.get('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('core.setup'))
    form = LoginForm()
    return render_template('user/login.html', form=form)


@bp.post('/login')
def login_post():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember.data)
        return redirect(url_for('core.setup'))
    return render_template('user/login.html', form=form)


@bp.get('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('core.setup'))
    form = RegisterForm()
    return render_template('user/register.html', form=form)


@bp.post('/register')
def register_post():
    form = RegisterForm()
    if form.validate_on_submit():
        User(username=form.username.data, email=form.email.data, password=form.password.data).save()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)


@bp.get('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@bp.get('/profile/')
@login_required
def profile():
    form = EditProfileForm()
    user = User.query.filter_by(id=current_user.id).first()
    form.username.data = user.username
    form.email.data = user.email
    return render_template('user/profile.html', form=form, user=user)


@bp.post('/profile/')
@login_required
def profile_post():
    form = EditProfileForm()
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.password = form.password.data
        user.update()
        flash('Your changes have been saved.')
        return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)

slideshow/templates/_footer.html
<footer class='footer fixed-bottom'>
    <div class='container text-center'>
        <p class='text-muted'>Powered by DS Slideshow</p>
    </div>
</footer>

slideshow/templates/_header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('core.index') }}"><h3>DS Slideshow</h3></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('core.setup') }}" class="nav-link">
                            <i class="fas fa-cogs"></i>&ensp;Settings
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('user.profile', username=current_user.username) }}" class="nav-link">
                            <i class="fas fa-user-cog"></i>&nbsp;Profile
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('user.logout') }}" class="nav-link">
                            <i class="fas fa-sign-out-alt"></i>Sign&nbsp;Out
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fab fa-"></i>Documentation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-30 p-0" href="https://github.com/Digital-Signage-Slideshow/DS_Slideshow"
                       target="_blank"><i
                            class="fab fa-github"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

slideshow/templates/index.html
<html>

<head>
	<title>DS Slideshow</title>
	<link rel = 'stylesheet' href = '{{ url_for ('static', filename = 'css/indexFormatting.css') }}'>
</head>

<body style = 'margin: 0; padding: 0'>

{% if not links and not images and not videos %}
	<div class = 'notFound'>
		<p>No Content to Display <br>To add content go to /setup or <a href = '/setup'>click here</a></p>
	</div>
{% endif %}

{% if links or images or videos %}
	<div class = 'slideshowDiv'>
		{% for image in images %}
			<img class = 'slideshowContent' src = '{{ url_for('static', filename = 'images/' + image) }}'>
		{% endfor %}

		{% for link in links %}
			<iframe src = '{{ link }}' class = 'slideshowContent'></iframe>
		{% endfor %}

		{% for video in videos %}
			<video class = 'slideshowContent'>
				<source src = '{{ url_for('static', filename = 'videos/' + video) }}' type = 'video/mp4'>
			</video>
		{% endfor %}
	</div>
{% endif %}

</body>

<script>
var slideIndex = 0;
{% if links %}
	var links = {{ links | safe}}
{% else %}
	var links = []
{% endif %}

{% if images %}
	var images = {{ images | safe }}
{% else %}
	var images = []
{% endif %}

{% if videos %}
	var videos = {{ videos | safe }}
{% endif %}

if (images.length > 0 || links.length > 0 || videos.length > 0){
	carousel();
}
else {
	setTimeout(refreshPage, 5000);
}

function refreshPage() {
	location.reload(true);
}

function carousel() {
	var i;
	var x = document.getElementsByClassName('slideshowContent');

	for (i = 0; i < x.length; i++) {
		x[i].style.display = 'none';
	
		if (x[i].nodeName == 'VIDEO') {
			x[i].pause();
		}
	}

	slideIndex++;
	if (slideIndex > x.length) {
		slideIndex = 1; location.reload();
	}

	x[slideIndex - 1].style.display = 'block';
	
	if (x[slideIndex - 1].nodeName == "VIDEO") {
		x[slideIndex - 1].play();
	}

	setTimeout(carousel, {{ rotation_speed }});
}
</script>

</html>