slideshow/blueprints/user/models.py
from slugify import slugify
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from slideshow.extensions import db
from slideshow.utils.sql import SQLMixin


class User(SQLMixin, UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    slug = db.Column(db.String(120), unique=True)
    email = db.Column(db.String(120), unique=True, nullable=True)
    password = db.Column(db.String())
    active = db.Column(db.Boolean, default=True)

    def gen_slug(self, username):
        self.slug = slugify(username)

    def hash_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        self.gen_slug(self.username)
        self.hash_password(self.password)

    def __repr__(self):
        return '<User: {}>'.format(self.username)

slideshow/blueprints/user/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, BooleanField, StringField
from wtforms.validators import EqualTo, ValidationError, InputRequired, Email
from .models import User


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired()])
    email = StringField('Email', validators=[Email()])
    password = PasswordField('Password', validators=[InputRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[InputRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        u = User.query.filter_by(username=username.data).first()

        if u is not None:
            raise ValidationError('a user already exists with that username')

    def validate_email(self, email):
        u = User.query.filter_by(email=email.data).first()

        if u is not None:
            raise ValidationError('a user already exists with that email')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])
    remember = BooleanField('RememberMe')
    submit = SubmitField('Login')


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired()])
    email = StringField('Email', validators=[InputRequired(), Email()])
    password = PasswordField('Password')
    confirm_password = PasswordField('Confirm Password', validators=[EqualTo('password')])

slideshow/blueprints/user/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
from flask_login import current_user, login_user, logout_user, login_required

from .forms import RegisterForm, LoginForm, EditProfileForm
from .models import User

bp = Blueprint('user', __name__, template_folder='templates', url_prefix='/user/')


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})


@bp.get('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('core.setup'))
    form = LoginForm()
    return render_template('user/login.html', form=form)


@bp.post('/login')
def login_post():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember.data)
        return redirect(url_for('core.setup'))
    return render_template('user/login.html', form=form)


@bp.get('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('core.setup'))
    form = RegisterForm()
    return render_template('user/register.html', form=form)


@bp.post('/register')
def register_post():
    form = RegisterForm()
    if form.validate_on_submit():
        User(username=form.username.data, email=form.email.data, password=form.password.data).save()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)


@bp.get('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@bp.get('/profile/')
@login_required
def profile():
    form = EditProfileForm()
    user = User.query.filter_by(id=current_user.id).first()
    form.username.data = user.username
    form.email.data = user.email
    return render_template('user/profile.html', form=form, user=user)


@bp.post('/profile/')
@login_required
def profile_post():
    form = EditProfileForm()
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.password = form.password.data
        user.update()
        flash('Your changes have been saved.')
        return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)

slideshow/blueprints/user/templates/user/login.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="flex align-center justify-center h-100">
        <form class="form-signin" action='' method='POST'>
            {{ form.csrf_token }}
            {% include 'macros/alerts.html' %}

            <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

            {{ form.username(class='form-control mb-1', placeholder='username') }}
            {{ form.password(class='form-control', placeholder='password') }}

            <div class="checkbox mb-3">
                <label>
                    {{ form.remember(class='checkbox') }} Remember Password
                </label>
            </div>

            <div class="row">
                <div class="col">
                    <a class="btn btn-block btn-sm btn-secondary" href="{{ url_for('user.register') }}">Register here</a>
                </div>
            </div>
            {{ form.submit(class = 'form-signin btn btn-lg btn-primary btn-block mt-2') }}
        </form>
    </div>
{% endblock %}

slideshow/blueprints/user/templates/user/profile.html
{% extends 'layouts/base.html' %}


{% block content %}
    <main>
        <div class="container">
            <div class="card mt-5">
                {% include 'macros/alerts.html' %}
                <div class="card-body">
                    <h2 class="card-title">Profile</h2>
                    <form action="" method="post">
                        {{ form.hidden_tag() }}
                        <div class="form-row">
                            <div class="from-group col-md-6">
                                {{ form.username.label }}
                                {{ form.username(class="form-control") }}
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.email.label }}
                                {{ form.email(class="form-control") }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                {{ form.password.label }}
                                {{ form.password(class="form-control", placeholder='XXXXXX') }}
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.confirm_password.label }}
                                {{ form.confirm_password(class="form-control", placeholder='XXXXXX') }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block page_scripts %}
    <script>
        $('.alert').alert()
    </script>
{% endblock %}

slideshow/blueprints/user/templates/user/register.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="flex align-center justify-center h-100">
        <form class="form-signin" action="{{ url_for('user.register') }}" method="post">
            {% include 'macros/alerts.html' %}

            <h1 class="h3 mb-3 font-weight-normal">Register Here</h1>

            {{ form.csrf_token }}
            {{ form.username(class='form-control mt-3 rounded-0', placeholder='Username') }}
            {{ form.email(type='email', class='form-control mt-3 rounded-0', placeholder="Email") }}
            {{ form.password(class='form-control mt-3 rounded-0', placeholder='Password') }}
            {{ form.confirm_password(class='form-control mt-3 rounded-0', placeholder='Confirm Password') }}

            {{ form.submit(class='form-signin btn btn-lg btn-primary btn-block mt-4') }}
        </form>
    </div>
{% endblock %}