slideshow/blueprints/core/models.py
from slideshow.extensions import db


class Content(db.Model):
    path = db.Column(db.String(), primary_key=True)
    priority = db.Column(db.Integer(), default=0)
    type = db.Column(db.String(4))  # img, link, vid
    interval = db.Column(db.Integer(), default=1000)  # in milliseconds
    active = db.Column(db.Boolean, default=True)

    def update_priority(self):
        self.priority = Content.query.count() + 1

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.update_priority()
        self.path = kwargs['path']
        self.type = kwargs['type']

    def __repr__(self):
        return f'{self.path}, {self.priority}'

slideshow/blueprints/core/views.py
from flask import render_template, request, redirect, url_for, flash, jsonify, Blueprint
from werkzeug.utils import secure_filename
from flask_login import login_required
import os

from slideshow.extensions import db
from slideshow.utils import allowed_file_extensions, get_file_extension, generate_uuid
from .models import Content

from config import UPLOAD_FOLDER

bp = Blueprint('core', __name__, template_folder='templates')

rotation_speed = 10000  # in miliseconds
upload_folder = UPLOAD_FOLDER


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})


@bp.get('/')
@login_required
def index():
    """
    Displays the index page.
    """
    return render_template('index.html')


@bp.get('/login')
def login():
    """
    Displays the login page.
    """
    return redirect(url_for('user.login'))


@bp.get('/register')
def register():
    """
    Displays the register page.
    """
    return redirect(url_for('user.register'))


@bp.get('/setup')
@login_required
def setup():
    """
    Displays the setup page.
    """
    contents = Content.query.all()
    return render_template('setup.html', contents=contents, rotation_speed=rotation_speed // 1000)


@bp.get('/slideshow')
def slideshow():
    """
    Displays the slideshow page.
    """
    contents = Content.query.filter_by(active=True).all()

    return render_template(
        'slideshow.html',
        contents=contents,
        rotation_speed=rotation_speed,
    )


@bp.post('/alter_rotation_speed')
def alter_rotation_speed():
    """
    Changes the rotation speed of the slideshow.
    """
    global rotation_speed

    try:
        rotation_speed = float(
            request.form.to_dict()['alter_rotation_speed']) * 1000
    except Exception as e:
        flash('Please enter a number')

    return redirect(url_for('core.setup'))


@bp.post('/upload_file/')
@login_required
def upload_file():
    """
    Uploads a file to the server.
    """
    file = request.files['file']

    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)

    if file and allowed_file_extensions(file.filename):
        # Upload the file to the uploads folder
        file_ext = get_file_extension(file.filename)
        filename = secure_filename(generate_uuid() + '.' + file_ext)
        file.save(os.path.join(upload_folder, filename))
        flash('File uploaded successfully')

        # Create a new content object
        content = Content(type='file', path=filename)
        db.session.add(content)
        db.session.commit()

        return redirect(url_for('core.setup'))


@bp.post('/remove_content')
@login_required
def remove_content():
    """
    Removes a content object from the server.
    Removes the file from the uploads' folder.
    """
    content_id = request.form.get('content_id')
    content = Content.query.filter_by(path=content_id)
    cont_object = content.first()

    if cont_object.type == 'file':
        os.remove(f'{upload_folder}/{cont_object.path}')
        content.delete()
    else:
        content.delete()
    db.session.commit()
    return redirect(url_for('core.setup'))


@bp.post('/upload_link')
@login_required
def upload_link():
    """
    Adds a link to the database.
    """
    link = request.form.to_dict()['upload_link']

    if link:
        # Create a new content object
        content = Content(type='link', path=link)
        db.session.add(content)
        db.session.commit()

        return redirect(url_for('core.setup'))
    else:
        flash('Please enter a link')
        return redirect(url_for('core.setup'))

slideshow/blueprints/core/templates/core/setup.html
{% extends 'layouts/base.html' %}


{% block main %}

    <section>
        <div class="container">
            <div class="row">
                <div class="col s12 m6 offset-md-3">
                    <h1>No Content</h1>
                </div>
            </div>
        </div>
    </section>




    <div class="fixed-action-btn">
        <a class="btn-floating btn-large blue accent-3 pulse">
            <i class="large material-icons">add</i>
        </a>
        <ul>
            <li>
                <a href="#videoContentModal"
                   class="btn-floating btn-large waves-effect modal-trigger">
                    <i class="large material-icons">videocam</i>
                </a>
            </li>
            <li>
                <a href="#imageContentModal" class="btn-floating btn-large waves-effect modal-trigger">
                    <i class="large material-icons">image</i>
                </a>
            </li>
            <li>
                <a href="#urlContentModal" class="btn-floating btn-large waves-effect modal-trigger">
                    <i class="large material-icons">add_link</i>
                </a>
            </li>
        </ul>
    </div>

    <div id="videoContentModal" class="modal rounded">
        <div class="modal-content">
            <h4 class="center-align">Add Video</h4>
        </div>
    </div>

    <div id="imageContentModal" class="modal rounded">
        <div class="modal-content">
            <h4 class="center-align">Add Image</h4>
        </div>
    </div>

    <div id="urlContentModal" class="modal rounded">
        <div class="modal-content">
            <h4 class="center-align">Add URL</h4>
        </div>
    </div>




{% endblock %}

{#{% block content %}#}
{#    <header>#}
{#        {% include 'macros/navbar.html' %}#}
{#    </header>#}
{##}
{#    <main>#}
{#        <div class="container">#}
{#            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"#}
{#                 aria-hidden="true">#}
{#                <div class="modal-dialog modal-lg" role="document">#}
{#                    <div class="modal-content">#}
{#                        <div class="modal-header">#}
{#                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">#}
{#                                <span aria-hidden="true">&times;</span>#}
{#                            </button>#}
{#                        </div>#}
{#                        <div class="modal-body">#}
{##}
{#                            <div class='container form-group rounded'>#}
{#                                <form action='{{ url_for('core.upload_link') }}' method='POST'>#}
{#                                    <h3>Link</h3>#}
{#                                    <p class='text-muted'>#}
{#                                        Please enter the entire path to the page. e.g. https://google.co.uk. Note some#}
{#                                        pages will not work with this software.#}
{#                                    </p>#}
{##}
{#                                    <div class='d-flex'>#}
{#                                        <input type='text' id='upload_link' name='upload_link' class='form-control'#}
{#                                               autocomplete='off' placeholder='Enter link' required>#}
{#                                        <input type='submit' value='Add Link' formmethod='POST'#}
{#                                               class='ml-4 btn btn-primary'>#}
{#                                    </div>#}
{#                                </form>#}
{##}
{#                                <form type='file' method='POST' enctype='multipart/form-data'#}
{#                                      action="{{ url_for('core.upload_file') }}">#}
{#                                    <h3>Image</h3>#}
{#                                    <p class='text-muted'>Supported formats: .png .jpg .jpeg</p>#}
{##}
{#                                    <!-- Custom Bootstrap File Input -->#}
{#                                    <div class='d-flex'>#}
{#                                        <div class="custom-file">#}
{##}
{#                                            <input type="file" class="custom-file-input" id="file" name='file' required>#}
{#                                            <label class="custom-file-label" for="customFile">Choose file</label>#}
{#                                        </div>#}
{##}
{#                                        <input type='submit' value='Upload' formmethod='POST'#}
{#                                               class='ml-4 btn btn-primary'>#}
{#                                    </div>#}
{#                                </form>#}
{##}
{#                                <form class='mt-5' action='{{ url_for('core.alter_rotation_speed') }}' method='POST'>#}
{#                                    <h3>Slideshow Speed</h3>#}
{#                                    <p class='text-muted'>Current Speed: {{ rotation_speed | int }} seconds</p>#}
{##}
{#                                    <div class='d-flex'>#}
{#                                        <input type='text' id='alter_rotation_speed' name='alter_rotation_speed'#}
{#                                               class='form-control' autocomplete='off' placeholder='Speed (s)'#}
{#                                               required/>#}
{#                                        <input type='submit' value='Change Speed' formmethod='POST'#}
{#                                               class='ml-4 btn btn-primary'>#}
{#                                    </div>#}
{#                                </form>#}
{#                            </div>#}
{##}
{#                        </div>#}
{##}
{#                        <div class="modal-footer mt-5">#}
{#                            <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>#}
{#                        </div>#}
{##}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            {% if contents %}#}
{#                <div class="album py-5 bg-light">#}
{##}
{#                <div class="container">#}
{#                    <button type="button" class="btn btn-primary ml-3" data-toggle="modal" data-target="#myModal">#}
{#                        Upload Content#}
{#                    </button>#}
{#                    <a href='/slideshow' class='btn btn-outline-secondary ml-3'>View Slideshow</a>#}
{##}
{#                <!-- Project Cards -->#}
{#                <div class="album py-5 bg-light">#}
{#                    <div class="container">#}
{##}
{#                        <h2 class='jumbotron-heading'>Content</h2>#}
{#                        <p class='text-muted'>Drag and drop slides to reorder the slideshow (not implemented yet)</p>#}
{#                        <hr>#}
{##}
{#                        <div class="row card-deck">#}
{#                            {% for content in contents %}#}
{#                                <div class="col-md-4 py-2">#}
{#                                    <div class="card mb-4 box-shadow h-100">#}
{#                                        {% if content.type == 'file' %}#}
{#                                            <img class="card-img-top"#}
{#                                                 src="{{ url_for('static', filename='images/slideshow_images/') }}{{ content.path }}"#}
{#                                                 alt="Card image cap" style='height: 50%; object-fit: cover'>#}
{#                                        {% elif content.type == 'link' %}#}
{#                                            <iframe class="card-img-top"#}
{#                                                    src="{{ content.path }}"#}
{#                                                    title="Card image cap"#}
{#                                                    style='height: 50%; object-fit: cover; border: 0;'></iframe>#}
{#                                        {% endif %}#}
{#                                        <div class="card-body">#}
{#                                            <hr>#}
{#                                            <p class="card-text text-muted">{{ content.path }}</p>#}
{#                                            <div style='width: 0; height: 0;'>#}
{#                                                <form id='{{ content.path }}'#}
{#                                                      action="{{ url_for('core.remove_content') }}"#}
{#                                                      method='POST'>#}
{#                                                    <input type='hidden' name='content_id' id='content_id'#}
{#                                                           value='{{ content.path }}'>#}
{#                                                </form>#}
{#                                            </div>#}
{#                                            <div class="d-flex justify-content-between align-items-center">#}
{#                                                <div class="btn-group">#}
{#                                                    <button name='submit' value='{{ content.path }}' type='submit'#}
{#                                                            class='btn btn-sm btn-outline-secondary'>Settings#}
{#                                                    </button>#}
{#                                                    <button form='{{ content.path }}' type='submit'#}
{#                                                            class="btn btn-sm btn-outline-secondary">Remove#}
{#                                                    </button>#}
{#                                                </div>#}
{#                                                <p class='text-muted'>{{ rotation_speed | int }}s</p>#}
{##}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            {% endfor %}#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            {% else %}#}
{#                <div class='text-center mt-5'>#}
{#                    <h1>No Content to Display</h1>#}
{#                    <p class='text-muted'>Click below to begin adding content</p>#}
{#                    <button type="button" class="btn btn-primary ml-3" data-toggle="modal" data-target="#myModal">Upload#}
{#                        Content#}
{#                    </button>#}
{#                </div>#}
{#            {% endif %}#}
{#            </div>#}
{#    </main>#}
{##}
{#    {% include 'macros/footer.html' %}#}
{##}
{#{% endblock %}#}

{% block page_scripts %}
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
{% endblock %}

slideshow/blueprints/core/templates/index.html
{% extends 'layouts/base.html' %}


{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">DS Slideshow</h1>
        <p class="lead">The fast, lightweight Digital Signage solution</p>
    </div>
{% endblock %}

slideshow/blueprints/core/templates/setup.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class='container form-group rounded'>
                        <form action='{{ url_for('core.upload_link') }}' method='POST'>
                            <h3>Link</h3>
                            <p class='text-muted'>
                                Please enter the entire path to the page. e.g. https://google.co.uk. Note some
                                pages will not work with this software.
                            </p>

                            <div class='d-flex'>
                                <input type='text' id='upload_link' name='upload_link' class='form-control'
                                       autocomplete='off' placeholder='Enter link' required>
                                <input type='submit' value='Add Link' formmethod='POST'
                                       class='ml-4 btn btn-primary'>
                            </div>
                        </form>

                        <form type='file' method='POST' enctype='multipart/form-data'
                              action="{{ url_for('core.upload_file') }}">
                            <h3>Image</h3>
                            <p class='text-muted'>Supported formats: .png .jpg .jpeg</p>

                            <!-- Custom Bootstrap File Input -->
                            <div class='d-flex'>
                                <div class="custom-file">

                                    <input type="file" class="custom-file-input" id="file" name='file' required>
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                </div>

                                <input type='submit' value='Upload' formmethod='POST'
                                       class='ml-4 btn btn-primary'>
                            </div>
                        </form>

                        <form class='mt-5' action='{{ url_for('core.alter_rotation_speed') }}' method='POST'>
                            <h3>Slideshow Speed</h3>
                            <p class='text-muted'>Current Speed: {{ rotation_speed | int }} seconds</p>

                            <div class='d-flex'>
                                <input type='text' id='alter_rotation_speed' name='alter_rotation_speed'
                                       class='form-control' autocomplete='off' placeholder='Speed (s)'
                                       required/>
                                <input type='submit' value='Change Speed' formmethod='POST'
                                       class='ml-4 btn btn-primary'>
                            </div>
                        </form>
                    </div>

                </div>

                <div class="modal-footer mt-5">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
                </div>

            </div>
        </div>
    </div>
    {% if contents %}
        <div class="album py-5 bg-light">

        <div class="container">
        <button type="button" class="btn btn-primary ml-3" data-toggle="modal" data-target="#myModal">
            Upload Content
        </button>
        <a href='/slideshow' class='btn btn-outline-secondary ml-3'>View Slideshow</a>

        <!-- Project Cards -->
        <div class="album py-5 bg-light">
            <div class="container">

                <h2 class='jumbotron-heading'>Content</h2>
                <p class='text-muted'>Drag and drop slides to reorder the slideshow (not implemented yet)</p>
                <hr>

                <div class="row card-deck">
                    {% for content in contents %}
                        <div class="col-md-4 py-2">
                            <div class="card mb-4 box-shadow h-100">
                                {% if content.type == 'file' %}
                                    <img class="card-img-top"
                                         src="{{ url_for('uploaded_file', filename=content.path) }}"
                                         alt="Card image cap" style='height: 50%; object-fit: cover'>
                                {% elif content.type == 'link' %}
                                    <iframe class="card-img-top"
                                            src="{{ content.path }}"
                                            title="Card image cap"
                                            style='height: 50%; object-fit: cover; border: 0;'></iframe>
                                {% endif %}
                                <div class="card-body">
                                    <hr>
                                    <p class="card-text text-muted">{{ content.path }}</p>
                                    <div style='width: 0; height: 0;'>
                                        <form id='{{ content.path }}'
                                              action="{{ url_for('core.remove_content') }}"
                                              method='POST'>
                                            <input type='hidden' name='content_id' id='content_id'
                                                   value='{{ content.path }}'>
                                        </form>
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <button name='submit' value='{{ content.path }}' type='submit'
                                                    class='btn btn-sm btn-outline-secondary'>Settings
                                            </button>
                                            <button form='{{ content.path }}' type='submit'
                                                    class="btn btn-sm btn-outline-secondary">Remove
                                            </button>
                                        </div>
                                        <p class='text-muted'>{{ rotation_speed | int }}s</p>

                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <div class='text-center mt-5'>
            <h1>No Content to Display</h1>
            <p class='text-muted'>Click below to begin adding content</p>
            <button type="button" class="btn btn-primary ml-3" data-toggle="modal" data-target="#myModal">Upload
                Content
            </button>
        </div>
    {% endif %}
</div>
{% endblock %}

{% block page_scripts %}
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
{% endblock %}

slideshow/blueprints/core/templates/slideshow.html
{% extends 'layouts/core.html' %}

{% block page_css %}
    <link rel='stylesheet' href='{{ url_for ('static', filename = 'css/ds_slider.css') }}'>
{% endblock %}

{% block content %}

    {% if contents %}
        <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                {% for content in contents %}
                    {% if content.priority == 1 %}
                        {% if content.type == 'file' %}
                            <div class="carousel-item active" data-interval="{{ content.interval }}">
                                <img src="{{ url_for('uploaded_file', filename=content.path) }}"
                                     class="d-block w-100 h-100"
                                     alt="...">
                            </div>
                        {% elif content.type == 'video' %}
                            <div class="carousel-item active" data-interval="{{ content.interval }}">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <video class="d-block w-100 h-100"
                                           src="{{ url_for('uploaded_file', filename=content.path) }}"
                                           autoplay="autoplay" loop="loop">
                                    </video>
                                </div>
                            </div>
                        {% else %}
                            <div class="carousel-item active" data-interval="{{ content.interval }}">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe src="{{ content.path }}" frameborder="0"></iframe>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                        {% if content.type == 'file' %}
                            <div class="carousel-item" data-interval="{{ content.interval }}">
                                <img src="{{ url_for('uploaded_file', filename=content.path) }}"
                                     class="d-block w-100 h-100"
                                     alt="...">
                            </div>
                        {% elif content.type == 'video' %}
                            <div class="carousel-item" data-interval="{{ content.interval }}">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <video class="d-block w-100 h-100"
                                           src="{{ url_for('uploaded_file', filename=content.path) }}"
                                           autoplay="autoplay" loop="loop">
                                    </video>
                                </div>
                            </div>
                        {% else %}
                            <div class="carousel-item" data-interval="{{ content.interval }}">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe src="{{ content.path }}" frameborder="0"></iframe>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% else %}
        <h1 class="display-1">No Contents</h1>
    {% endif %}

{% endblock %}